### ISSUE TITLE
Ayudame a instalarlo

### ISSUE THREAD

**Issue by johnfelipe** [CodeandoMexico/iniciativas-datamx#1]
Ayudame por favor, gracias

**Comment by poguez** [comment]
¿Necesitas instalar DemocracyOS?

**Comment by johnfelipe** [comment]
Efectivamente, puedes ayudarme,  me presenta varios errores

**Comment by poguez** [comment]
Puedes ver más detalles con los creadores de la app en https://github.com/DemocracyOS/app

**Comment by johnfelipe** [comment]
Pero me dan ciertos errores, tu no lo has instalado

**Comment by poguez** [comment]
Aun no :-1:  :disappointed: 
Por eso revisa con los creadores :smile:

**Comment by johnfelipe** [comment]
Y si lo instalamos juntos, a mi me da error cuando hago el make.
